# Generated by Django 2.0.2 on 2018-03-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drafter',
            name='rounds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drafter',
            name='turns_per_round',
            field=models.IntegerField(default=0),
        ),
    ]
