# Generated by Django 2.0.2 on 2018-03-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0002_auto_20180317_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drafter',
            name='draft_turn',
            field=models.IntegerField(default=1),
        ),
    ]
