# Generated by Django 2.0.2 on 2018-03-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0003_auto_20180317_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='drafter',
            name='overall_pick',
            field=models.IntegerField(default=1),
        ),
    ]
