# Generated by Django 2.0.2 on 2018-03-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0004_drafter_overall_pick'),
    ]

    operations = [
        migrations.AddField(
            model_name='drafter',
            name='current_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='drafter',
            name='draft_goalies',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='drafter',
            name='total_rounds',
            field=models.IntegerField(default=1),
        ),
    ]
