# Generated by Django 2.0.2 on 2018-03-22 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0007_drafter_total_picks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drafter',
            name='rounds',
        ),
    ]
