# Generated by Django 2.0.2 on 2018-03-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0008_remove_drafter_rounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='drafter',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
