# Generated by Django 2.0.2 on 2018-03-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0002_squad_draft_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
