# Generated by Django 2.0.2 on 2018-03-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0003_auto_20180311_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
