# Generated by Django 2.0.2 on 2018-02-10 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('forward_pos', models.BooleanField()),
                ('defence_pos', models.BooleanField()),
                ('rightwing_pos', models.BooleanField()),
                ('leftwing_pos', models.BooleanField()),
                ('centre_pos', models.BooleanField()),
                ('goalie_pos', models.BooleanField()),
                ('games_played', models.IntegerField()),
                ('points', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('pp_goals', models.IntegerField()),
                ('pp_assists', models.IntegerField()),
                ('pp_points', models.IntegerField()),
                ('gw_goals', models.IntegerField()),
                ('sh_goals', models.IntegerField()),
                ('blocks', models.IntegerField()),
                ('hits', models.IntegerField()),
                ('faceoff_wins', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
        ),
    ]
