# Generated by Django 2.0.2 on 2018-03-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_auto_20180310_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='owner_amount',
            field=models.IntegerField(default=0),
        ),
    ]
