# Generated by Django 2.0.2 on 2018-03-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_auto_20180311_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
