# Generated by Django 2.0.2 on 2018-02-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('shortform', models.CharField(max_length=3, null=True)),
                ('in_playoffs', models.BooleanField(default=False)),
            ],
        ),
    ]
