# Generated by Django 2.0.2 on 2018-02-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=3, null=True)),
        ),
    ]
